language: php
php:
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly

install:
  - composer install

script:
  - make test

branches:
  only:
    - master

notifications:
  email: false
